const labels={AGE:"年龄",HEALTH:"体魄",INSIGHT:"洞察",COMPASSION:"仁心",COURAGE:"勇气",REPUTATION:"声望"};
const state={AGE:0,HEALTH:5,INSIGHT:0,COMPASSION:0,COURAGE:0,REPUTATION:0};
const ui={chapter:document.querySelector("#chapter"),progress:document.querySelector("#progress"),title:document.querySelector("#eventTitle"),text:document.querySelector("#eventText"),choices:document.querySelector("#choices"),start:document.querySelector("#startButton"),ambient:document.querySelector("#ambient"),sound:document.querySelector("#soundToggle")};
let events=[],cursor=0;
function updateLedger(){for(const[key,value]of Object.entries(state)){const target=document.querySelector(`[data-stat="${key}"]`);if(target)target.textContent=value}}
function summarize(effects){return effects.filter(effect=>labels[effect.target]).map(effect=>`${labels[effect.target]} ${effect.value>=0?"+":""}${effect.value}`).join(" · ")}
function choose(choice){for(const effect of choice.effects??[]){if(effect.target in state)state[effect.target]+=Number(effect.value)||0}state.AGE=Math.min(99,Math.floor((cursor+1)/2));cursor+=1;updateLedger();render()}
function ending(){const ranked=Object.entries(state).filter(([key])=>key!=="AGE").sort((a,b)=>b[1]-a[1]);ui.chapter.textContent="此世已尽";ui.progress.textContent="100 / 100";ui.title.textContent="一灯照过百年";ui.text.textContent=`江照野走完了这一世。最高属性是${labels[ranked[0][0]]}（${ranked[0][1]}）。正式《创世之初》拥有独立人物、世界与事件库，本页只展示开源引擎的最小游戏流程。`;ui.choices.replaceChildren();const button=document.createElement("button");button.className="choice primary";button.textContent="再开一世";button.addEventListener("click",()=>location.reload());ui.choices.append(button)}
function render(){if(cursor>=events.length)return ending();const event=events[cursor];ui.chapter.textContent=event.chapter;ui.progress.textContent=`${cursor+1} / ${events.length}`;ui.title.textContent=event.title;ui.text.textContent=event.text;ui.choices.replaceChildren();for(const choice of event.choices??[]){const button=document.createElement("button");const effects=summarize(choice.effects??[]);button.className="choice";button.textContent=effects?`${choice.label}　｜　${effects}`:choice.label;button.addEventListener("click",()=>choose(choice));ui.choices.append(button)}}
async function start(){ui.start.disabled=true;ui.start.textContent="载入此世……";const response=await fetch("../examples/demo-world-100.zh-CN.json");if(!response.ok)throw new Error(`无法载入演示事件：${response.status}`);events=(await response.json()).events;render()}
ui.start.addEventListener("click",()=>start().catch(error=>{ui.text.textContent=error.message;ui.start.disabled=false;ui.start.textContent="重新载入"}));
ui.sound.addEventListener("click",async()=>{if(ui.ambient.paused){await ui.ambient.play();ui.sound.textContent="♫ 关闭音乐";ui.sound.setAttribute("aria-pressed","true")}else{ui.ambient.pause();ui.sound.textContent="♫ 开启音乐";ui.sound.setAttribute("aria-pressed","false")}});
